GET http://localhost:8080/products
Content-Type: application/json

###

POST http://localhost:8080/products
Content-Type: application/json

{
  "seller": "anonymous",
  "name": "Laptop Asus Vivobook",
  "description": "Laptop Asus Vivobook",
  "item": 4,
  "price": 18000000
}

###

DELETE http://localhost:8080/products/1
Content-Type: application/json